import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "ChatGPT Messenger",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div className="flex">
					<div className="bg-[#202123] max-w-xs overflow-y-auto h-screen md:min-w-[20rem]">
						<Sidebar />
					</div>

					{/* Client Provider - Notification */}

					<div className="bg-[#343541] flex-1">{children}</div>
				</div>
			</body>
		</html>
	);
}
