import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "ChatGPT Messenger",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div className="flex">
					{/* <Sidebar /> */}

					{/* Client Provider - Notification */}

					<div className="bg-[#343541] flex-1">{children}</div>
				</div>
			</body>
		</html>
	);
}
